import 'package:oop/business_logic/models/menu_item.dart';
import 'package:oop/business_logic/models/restaurants_info.dart';

const restaurants = [
  RestaurantInfo(
    id: '1',
    name: 'The Gourmet Spot',
    logo: 'assets/farm.png',
    distance: '1.2 miles',
    description: 'A cozy spot offering a fusion of modern and traditional cuisines. The Gourmet Spot prides itself on its exquisite blend of flavors and innovative dishes, providing a dining experience that tantalizes the taste buds and leaves a lasting impression. With a warm and inviting ambiance, it is perfect for both casual meals and special occasions.',
    rating: '4.8',
    tag: 'Fresh',
    items: [
      MenuItem('1.1', 'Truffle Risotto', '25.99', 'assets/pasta.jpeg'),
      MenuItem('1.2', 'Filet Mignon', '39.99', 'assets/pasta.jpeg'),
      MenuItem('1.3', 'Lobster Bisque', '19.99', 'assets/pasta.jpeg'),
      MenuItem('1.4', 'Duck Confit', '28.99', 'assets/pasta.jpeg'),
      MenuItem('1.5', 'Chocolate Soufflé', '12.99', 'assets/pasta.jpeg'),
      MenuItem('1.6', 'Wine Pairing', '15.99', 'assets/pasta.jpeg'),
    ],
  ),
  RestaurantInfo(
    id: '2',
    name: 'Pizza Paradise',
    logo: 'assets/pizza_logo.png',
    distance: '0.5 miles',
    description: 'A family-friendly pizzeria with a wide variety of toppings and styles. Pizza Paradise is the go-to place for pizza lovers, offering everything from classic Margherita to inventive specialty pies. Its welcoming environment makes it ideal for family gatherings and casual outings, ensuring a delightful experience for everyone.',
    rating: '4.5',
    tag: 'Popular',
    items: [
      MenuItem('2.1', 'Margherita Pizza', '14.99', 'assets/pasta.jpeg'),
      MenuItem('2.2', 'Pepperoni Pizza', '16.99', 'assets/pasta.jpeg'),
      MenuItem('2.3', 'BBQ Chicken Pizza', '18.99', 'assets/pasta.jpeg'),
      MenuItem('2.4', 'Veggie Supreme Pizza', '15.99', 'assets/pasta.jpeg'),
      MenuItem('2.5', 'Hawaiian Pizza', '17.99', 'assets/pasta.jpeg'),
      MenuItem('2.6', 'Cheese Breadsticks', '8.99', 'assets/pasta.jpeg'),
    ],
  ),
  RestaurantInfo(
    id: '3',
    name: 'Sushi Haven',
    logo: 'assets/Japanese_food.png',
    distance: '2.3 miles',
    description: 'A sushi lover\'s dream with fresh fish and creative rolls. Sushi Haven is renowned for its artistic presentation and high-quality ingredients, making it a top destination for sushi enthusiasts. The restaurant offers a serene atmosphere where guests can savor meticulously crafted rolls and sashimi.',
    rating: '4.7',
    tag: 'Japanese',
    items: [
      MenuItem('3.1', 'California Roll', '12.99', 'assets/pasta.jpeg'),
      MenuItem('3.2', 'Spicy Tuna Roll', '14.99', 'assets/pasta.jpeg'),
      MenuItem('3.3', 'Dragon Roll', '16.99', 'assets/pasta.jpeg'),
      MenuItem('3.4', 'Salmon Sashimi', '19.99', 'assets/pasta.jpeg'),
      MenuItem('3.5', 'Miso Soup', '5.99', 'assets/pasta.jpeg'),
      MenuItem('3.6', 'Green Tea Ice Cream', '6.99', 'assets/pasta.jpeg'),
    ],
  ),
  RestaurantInfo(
    id: '4',
    name: 'Veggie Delight',
    logo: 'assets/vegan.png',
    distance: '1.1 miles',
    description: 'A vegetarian and vegan restaurant with a variety of healthy options. Veggie Delight caters to health-conscious diners with its diverse menu of plant-based dishes. The restaurant emphasizes fresh, organic ingredients and innovative cooking techniques, offering a vibrant and wholesome dining experience.',
    rating: '4.4',
    tag: 'Vegan',
    items: [
      MenuItem('4.1', 'Grilled Vegetable Platter', '13.99', 'assets/pasta.jpeg'),
      MenuItem('4.2', 'Vegan Burger', '11.99', 'assets/pasta.jpeg'),
      MenuItem('4.3', 'Quinoa Salad', '10.99', 'assets/pasta.jpeg'),
      MenuItem('4.4', 'Stuffed Peppers', '12.99', 'assets/pasta.jpeg'),
      MenuItem('4.5', 'Vegan Chocolate Cake', '7.99', 'assets/pasta.jpeg'),
      MenuItem('4.6', 'Fresh Juice', '5.99', 'assets/pasta.jpeg'),
    ],
  ),
  RestaurantInfo(
    id: '5',
    name: 'Taco Town',
    logo: 'assets/taco.png',
    distance: '0.8 miles',
    description: 'A casual spot serving up authentic Mexican tacos and more. Taco Town is known for its vibrant flavors and street-food-inspired menu, making it a favorite among taco enthusiasts. The laid-back atmosphere and quick service make it a great spot for a tasty, informal meal.',
    rating: '4.3',
    tag: 'Mexican',
    items: [
      MenuItem('5.1', 'Chicken Taco', '3.99', 'assets/pasta.jpeg'),
      MenuItem('5.2', 'Beef Taco', '4.49', 'assets/pasta.jpeg'),
      MenuItem('5.3', 'Fish Taco', '4.99', 'assets/pasta.jpeg'),
      MenuItem('5.4', 'Vegetarian Taco', '3.99', 'assets/pasta.jpeg'),
      MenuItem('5.5', 'Churros', '5.49', 'assets/pasta.jpeg'),
      MenuItem('5.6', 'Margarita', '7.99', 'assets/pasta.jpeg'),
    ],
  ),
  RestaurantInfo(
    id: '6',
    name: 'Pasta Palace',
    logo: 'assets/fast_food.png',
    distance: '1.5 miles',
    description: 'An Italian restaurant with a range of classic and contemporary pasta dishes. Pasta Palace offers an extensive menu of both traditional and innovative pasta creations, making it a haven for pasta aficionados. The restaurant\'s elegant yet cozy setting is perfect for enjoying a hearty Italian meal.',
    rating: '4.7',
    tag: 'Italian',
    items: [
      MenuItem('6.1', 'Spaghetti Carbonara', '14.99', 'assets/pasta.jpeg'),
      MenuItem('6.2', 'Fettuccine Alfredo', '13.99', 'assets/pasta.jpeg'),
      MenuItem('6.3', 'Lasagna', '16.99', 'assets/pasta.jpeg'),
      MenuItem('6.4', 'Pesto Penne', '13.99', 'assets/pasta.jpeg'),
      MenuItem('6.5', 'Garlic Bread', '6.99', 'assets/pasta.jpeg'),
      MenuItem('6.6', 'Tiramisu', '8.99', 'assets/pasta.jpeg'),
    ],
  ),
  RestaurantInfo(
    id: '7',
    name: 'Bakery Bliss',
    logo: 'assets/pink_cake.png',
    distance: '0.4 miles',
    description: 'A delightful bakery offering a wide range of freshly baked goods. Bakery Bliss is a haven for those with a sweet tooth, featuring an array of pastries, cakes, and breads that are baked daily. The cozy shop invites customers to indulge in delicious treats while enjoying a warm and friendly atmosphere.',
    rating: '4.9',
    tag: 'Bakery',
    items: [
      MenuItem('7.1', 'Croissant', '2.99', 'assets/pasta.jpeg'),
      MenuItem('7.2', 'Chocolate Chip Cookie', '1.49', 'assets/pasta.jpeg'),
      MenuItem('7.3', 'Blueberry Muffin', '2.49', 'assets/pasta.jpeg'),
      MenuItem('7.4', 'Cinnamon Roll', '3.49', 'assets/pasta.jpeg'),
      MenuItem('7.5', 'Red Velvet Cupcake', '2.99', 'assets/pasta.jpeg'),
      MenuItem('7.6', 'Cheesecake Slice', '4.99', 'assets/pasta.jpeg'),
    ],
  ),
];
