// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVeDy1CtTo7O8RJiDymT3HTB-tioE8R14',
    appId: '1:3480710816:web:3e11d11466f58e8de663c5',
    messagingSenderId: '3480710816',
    projectId: 'restaurants-a97bb',
    authDomain: 'restaurants-a97bb.firebaseapp.com',
    storageBucket: 'restaurants-a97bb.appspot.com',
    measurementId: 'G-CH13YDCGQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXECKGQh34Yu4vnOgGtmQ5TotmQu1X6vo',
    appId: '1:3480710816:android:e1de052439be1756e663c5',
    messagingSenderId: '3480710816',
    projectId: 'restaurants-a97bb',
    storageBucket: 'restaurants-a97bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1yIy9DAKl1Mnq0iSAoIzk-pI5g_cTnsY',
    appId: '1:3480710816:ios:1c5c6a7cec282028e663c5',
    messagingSenderId: '3480710816',
    projectId: 'restaurants-a97bb',
    storageBucket: 'restaurants-a97bb.appspot.com',
    iosBundleId: 'com.example.oop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1yIy9DAKl1Mnq0iSAoIzk-pI5g_cTnsY',
    appId: '1:3480710816:ios:1c5c6a7cec282028e663c5',
    messagingSenderId: '3480710816',
    projectId: 'restaurants-a97bb',
    storageBucket: 'restaurants-a97bb.appspot.com',
    iosBundleId: 'com.example.oop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVeDy1CtTo7O8RJiDymT3HTB-tioE8R14',
    appId: '1:3480710816:web:de631837f2a2e073e663c5',
    messagingSenderId: '3480710816',
    projectId: 'restaurants-a97bb',
    authDomain: 'restaurants-a97bb.firebaseapp.com',
    storageBucket: 'restaurants-a97bb.appspot.com',
    measurementId: 'G-ETDDPXFCVP',
  );
}
